version: '3.8'

services:
    app:
        build:
            context: .
        container_name: bookshop_app
        ports:
            - "80:80"
        volumes:
            - .:/var/www/html/bookshop
        depends_on:
            - db
        environment:
            DB_CONNECTION: mysql
            DB_HOST: db
            DB_PORT: 3306
            DB_DATABASE: bookshop
            DB_USERNAME: root
            DB_PASSWORD: root

    db:
        image: mysql:5.7
        container_name: bookshop_db
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: bookshop
            MYSQL_USER: root
            MYSQL_PASSWORD: root
        volumes:
            - db_data:/var/lib/mysql

volumes:
    db_data:
